const words = [
    // Top 200 most common English words
    "the", "be", "of", "and", "a", "to", "in", "he", "have", "it",
    "that", "for", "they", "i", "with", "as", "not", "on", "she", "at",
    "by", "this", "we", "you", "do", "but", "from", "or", "which", "one",
    "would", "all", "will", "there", "say", "who", "make", "when", "can", "more",
    "if", "no", "man", "out", "other", "so", "what", "time", "up", "go",
    "about", "than", "into", "could", "state", "only", "new", "year", "some", "take",
    "come", "these", "know", "see", "use", "get", "like", "then", "first", "any",
    "work", "now", "may", "such", "give", "over", "think", "most", "even", "find",
    "day", "also", "after", "way", "many", "must", "look", "before", "great", "back",
    "through", "long", "where", "much", "should", "well", "people", "down", "own", "just",
    "because", "good", "each", "those", "feel", "seem", "how", "high", "too", "place",
    "little", "world", "very", "still", "nation", "hand", "old", "life", "tell", "write",
    "become", "here", "show", "house", "both", "between", "need", "mean", "call", "develop",
    "under", "last", "right", "move", "thing", "general", "school", "never", "same", "another",
    "begin", "while", "number", "part", "turn", "real", "leave", "might", "want", "point",
    "form", "off", "child", "few", "small", "since", "against", "ask", "late", "home",
    "interest", "large", "person", "end", "open", "public", "follow", "during", "present", "without",
    "again", "hold", "govern", "around", "possible", "head", "consider", "word", "program", "problem",
    "however", "lead", "system", "set", "order", "eye", "plan", "run", "keep", "face",
    "fact", "group", "play", "stand", "increase", "early", "course", "change", "help", "line",

    // Extended common words (201-500)
    "city", "tree", "cross", "farm", "hard", "start", "might", "story", "saw", "far",
    "sea", "draw", "left", "late", "run", "close", "night", "real", "life", "few",
    "north", "carry", "side", "been", "below", "able", "always", "land", "light", "next",
    "near", "food", "door", "above", "stop", "often", "until", "mile", "river", "car",
    "feet", "care", "second", "book", "enough", "plain", "girl", "usual", "young", "ready",
    "important", "answer", "body", "serve", "watch", "field", "break", "purpose", "reach", "letter",
    "class", "mother", "father", "country", "build", "center", "nature", "sleep", "money", "power",
    "together", "though", "every", "music", "water", "paper", "often", "earth", "thought", "head",
    "stand", "group", "idea", "table", "area", "drive", "clear", "voice", "press", "grow",
    "dark", "whole", "pull", "free", "bring", "nothing", "real", "seem", "behind", "along",
    "learn", "study", "mark", "appear", "speak", "listen", "walk", "able", "strong", "believe",
    "happen", "morning", "known", "reason", "south", "west", "top", "company", "name", "age",
    "human", "try", "final", "done", "already", "mind", "turn", "matter", "study", "room",
    "future", "color", "black", "white", "green", "blue", "heart", "wonder", "kind", "along",
    "love", "town", "church", "front", "week", "month", "live", "force", "today", "war",
    "toward", "half", "street", "among", "face", "fire", "full", "road", "rest", "pass",
    "stay", "deep", "space", "act", "true", "ground", "complete", "train", "rock", "toward",
    "different", "example", "question", "least", "morning", "picture", "language", "certain", "surface", "produce",
    "building", "remember", "measure", "contain", "product", "describe", "bring", "explain", "support", "provide",
    "moment", "notice", "remain", "process", "figure", "simple", "common", "member", "nothing", "social",
    "window", "father", "mother", "rather", "animal", "record", "appear", "special", "enough", "toward",
    "begin", "effort", "result", "modern", "police", "effect", "period", "minute", "strong", "occur",
    "expect", "travel", "return", "health", "enjoy", "create", "start", "issue", "market", "system",
    "action", "direct", "spend", "level", "board", "single", "clear", "share", "price", "method",
    "event", "natural", "value", "basis", "control", "office", "demand", "sound", "treat", "model",
    "accept", "offer", "discuss", "recent", "piece", "reduce", "require", "likely", "former", "spring",
    "report", "summer", "growth", "income", "beyond", "choose", "apply", "assume", "finger", "manage",
    "design", "agency", "degree", "center", "charge", "active", "suffer", "teacher", "similar", "worker",
    "debate", "window", "market", "option", "budget", "decade", "region", "image", "exist", "dream",

    // Extended words (501-800) — slightly harder
    "abandon", "abstract", "academy", "achieve", "acquire", "adapt", "adequate", "adjust", "advance", "advocate",
    "afford", "airport", "alcohol", "align", "alliance", "alter", "amateur", "ambition", "analyze", "ancient",
    "angle", "anxious", "appeal", "archive", "arrange", "assault", "assembly", "assess", "asset", "assign",
    "assist", "athlete", "attempt", "author", "average", "barrier", "battery", "benefit", "besides", "blanket",
    "borrow", "boundary", "bracket", "breath", "briefly", "broadly", "cabinet", "capable", "capture", "carbon",
    "chapter", "chronic", "circuit", "climate", "cluster", "coach", "coastal", "collect", "colonial", "combine",
    "comfort", "command", "comment", "commit", "complex", "compose", "concept", "conduct", "confirm", "connect",
    "consent", "consist", "constant", "consult", "consumer", "context", "contrast", "convert", "correct", "counter",
    "county", "courage", "coverage", "creation", "creature", "criminal", "critical", "crucial", "cultural", "current",
    "customer", "database", "deadline", "decline", "deficit", "deliver", "density", "deposit", "despite", "destroy",
    "detail", "detect", "develop", "digital", "display", "dispute", "distant", "distinct", "district", "divorce",
    "domestic", "dominant", "dramatic", "drawing", "dynasty", "economy", "edition", "educate", "elderly", "election",
    "element", "embrace", "emotion", "emphasis", "empire", "enabled", "encounter", "enormous", "ensure", "enterprise",
    "entire", "entrance", "episode", "equation", "equip", "erosion", "essence", "estate", "estimate", "eternal",
    "evaluate", "evident", "evolve", "examine", "exceed", "exclude", "execute", "exercise", "exhibit", "expand",
    "exploit", "explore", "exposure", "extend", "external", "extract", "extreme", "fabric", "faculty", "failure",
    "fashion", "feature", "federal", "fiction", "finance", "fishing", "fitness", "flexible", "formula", "fortune",
    "forward", "founder", "fraction", "fragile", "fragment", "freedom", "frequent", "frustrate", "function", "funding",
    "gallery", "gambling", "gateway", "genuine", "gesture", "glimpse", "glorious", "goddess", "gradually", "graduate",
    "grocery", "guardian", "habitat", "handful", "hardware", "harmony", "harvest", "headline", "heritage", "highway",
    "horizon", "hostile", "household", "housing", "humble", "hunting", "identity", "ideology", "ignorance", "illegal",
    "illusion", "imagine", "immense", "immigrant", "immune", "implication", "implicit", "impose", "impress", "impulse",
    "incident", "incline", "include", "indicate", "indirect", "industry", "infinite", "informal", "inherent", "initial",
    "innocent", "innovate", "inspect", "instance", "instant", "install", "integral", "intense", "interact", "interior",
    "internal", "interval", "intimate", "invasion", "investor", "involve", "isolate", "journal", "justice", "justify",
    "kitchen", "kingdom", "landmark", "largely", "lasting", "lateral", "launch", "lawsuit", "lecture", "leisure",
    "liberal", "liberty", "license", "likewise", "literary", "living", "location", "logical", "loyalty", "luxury",
    "magnetic", "mainland", "maintain", "majority", "mansion", "massive", "meaning", "measure", "mention", "mineral",
    "minister", "minority", "miracle", "mission", "mixture", "moderate", "molecule", "monitor", "mortgage", "mystery",
    "narrative", "negative", "neither", "nervous", "neutral", "nightmare", "numerous", "nursing", "obstacle", "obvious"
];

export default words;
